services:
  neoris-cuenta:
    build: ./neoris
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:8081"
    networks:
      - app-network
  
  neoris-cliente:
    build: ./neoris-cliente
    depends_on:
      neoris-cuenta:
        condition: service_started
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - ACCOUNT_SERVICE_URL=${ACCOUNT_SERVICE_URL}
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge